### ISSUE TITLE
Decide on URLs for the Debian 12 PPA

### ISSUE THREAD

**Issue by CyrilBrulebois** [PiRogueToolSuite/ppa#3]
# Current status: 1 PPA, Debian 11

At the moment we have https://pts-project.org/ppa/ that's giving users a `curl` command that configures the following:

```
deb https://piroguetoolsuite.github.io/ppa/pirogue ./
deb https://piroguetoolsuite.github.io/ppa/pirogue-3rd-party ./
```

and the following are working as well, even if there is no indexing (add `Release` at the end to get a file, avoiding the 404):

- https://pts-project.org/ppa/pirogue/
- https://pts-project.org/ppa/pirogue-3rd-party/

Those two directories are deployed via GitHub Pages, at the “root” of https://pts-project.org/ppa/

# Investigating user-facing layouts

We have all Debian 11 packages “flattened” in each directory, and it'd be a very bad idea to try and throw Debian 12 packages into these directories. See the last component of each `deb` line: `./`. For “regular” Debian repositories, we would have a base URL (like those above), then a suite (e.g. `bullseye` or `bookworm`), and finally one or more components (e.g. `main`, `contrib`, etc.). Switching to “regular” Debian repositories would mean some layout changes, and documentation changes as well anyway, and would make it slightly harder to maintain.

It looks to me the easiest would be to keep using “flattened” directories, with different URLs/entrypoints. Assuming we're happy to keep the `pirogue` vs. `pirogue-3rd-party` distinction, here are a few proposals. I'm not trying to make things appealing, it's easy enough to adjust *names* once the layout is clarified.

- Debian-version-based:
  - https://pts-project.org/ppa/pirogue-debian12/
  - https://pts-project.org/ppa/pirogue-debian12-3rd-party/

- Codename-based:
  - https://pts-project.org/ppa/pirogue-bookworm/
  - https://pts-project.org/ppa/pirogue-bookworm-3rd-party/

- PiRogue-version-based (assuming there would be a PiRogue major version bump — this would seem unlikely and weird):
  - https://pts-project.org/ppa/pirogue2/
  - https://pts-project.org/ppa/pirogue2-3rd-party/

Note that in each case, we're still publishing things in the https://pts-project.org/ppa/ “root”.

# Implementation

All the above solutions are very similar: they can be implemented by adding new directories alongside the existing ones in this repository, and letting the GitHub Pages logic do its magic. A while back, we mentioned that we might want to use a different repository altogether, and maybe retire this initial repository after a while.

I don't have a strong opinion on which path we should follow. Keeping everything in the same place means an ever-growing repository with things that are going to be obsolete and can't be cleaned up. That might be OK though, since the PPA isn't that big. If we go for a separate PPA for Debian 12, I'm not sure whether it's feasible for the GitHub Pages settings in that other repository to also publish in the same https://pts-project.org/ppa/ “root”. If that's not the case, we might need to switch to a different “root”, which could mean slightly different layouts compared to the first options mentioned above.

- Debian-version-based:
  - https://pts-project.org/ppa-debian12/pirogue/
  - https://pts-project.org/ppa-debian12/pirogue-3rd-party/

- Codename-based:
  - https://pts-project.org/ppa-bookworm/pirogue/
  - https://pts-project.org/ppa-bookworm/pirogue-3rd-party/

- PiRogue-version-based (assuming there would be a PiRogue major version bump — this would seem unlikely and weird):
  - https://pts-project.org/ppa-2/pirogue/
  - https://pts-project.org/ppa-2/pirogue-3rd-party/

# Timing

While I'd like to underline the necessity to make an informed decision about the layout, since it's going to be mentioned in user-facing instructions (including `curl` calls to set everything up), it looks to me this might be a blocker rather soon: since we have a plan for almost all packages now, we're close to reaching the point where we'll need to publish packages “somewhere”. I suggest we make this issue very high priority.

**Comment by U039b** [comment]
I would prefer this schema: 
* `https://pts-project.org/ppa/debian-11/pirogue*/ `
* `https://pts-project.org/ppa/debian-12/pirogue*/ `
* ...

**Comment by CyrilBrulebois** [comment]
Perfect, let's do that.

I'll check whether symlinks are suported in GitHub pages (I really hope they are). If they are, I'll prepare the move from existing locations to under `debian-11/`, then updating documentation (probably just proposing PRs).

**Comment by CyrilBrulebois** [comment]
Symlinks confirmed working as expected.

**Comment by CyrilBrulebois** [comment]
Next problem: the repository is getting big, and we can only publish a given repository as https://<hostname>/<repository> so we can't implement `https://pts-project.org/ppa/debian-N/` from various `ppa-debian-N` repositories.

I'm not sure we can do better than `https://pts-project.org/ppa-debian-N/` if we want/need to use different repositories.

I'll try and think a little more about this. Letting GitHub take care of the hosting via Pages is not something that we should consider abandoning lightly…

**Comment by CyrilBrulebois** [comment]
Another option that might be slightly nicer-looking could be URLs like these:

https://ppa.pts-project.org/debian-12/pirogue
https://ppa.pts-project.org/debian-12/pirogue-3rd-party

or what I'd like a little better (but it's really a matter of taste):

https://packages.pts-project.org/debian-12/pirogue
https://packages.pts-project.org/debian-12/pirogue-3rd-party

This is assuming:

1. We can publish `debian-N` repositories to `https://<subdomain>.pts-project.org/<repository>` — IOW: we're not limited to publishing under the main `https://pts-project.org/` domain.
1. @U039b is happy with such a setup!

In which case, I'm happy to set up a `debian-12` repository, and start stashing packages there.

If we go that route, maybe not touching the existing `ppa` repository, URL, etc. would be best. We would just retire it after a while, moving the `ppa/` landing page (and key material etc.) under the website repository?

**Comment by CyrilBrulebois** [comment]
[REDACTED COMMENT]

This was about various attempts to see what could be achieved and what couldn't. Further discussion led to the comments and the resolution found below.

**Comment by U039b** [comment]
The URL for the Debian 12 PPA is: `https://pts-project.org/debian-12/`

**Comment by CyrilBrulebois** [comment]
OK, `ppa.git` changes reverted: it says as it is, will get cloned into `debian-11.git`, to be published as `https://pts-project.org/debian-11/` alongside the existing `https://pts-project.org/ppa/` for consistency with the new naming scheme.

Closing accordingly.
